steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:latest']
images:
  - 'europe-west9-docker.pkg.dev/${PROJECT_ID}/${_APP_NAME}-repo/${_APP_NAME}:latest'
substitutions:
  _APP_NAME: 'flappy-h2'
options:
  logging: CLOUD_LOGGING_ONLY
